Algoritmo "semnome"
// Função: Ler nome e fazer a junção do nome com o sobrenomne

// Autor: Guilherme Nasciment de Oliveira
// Data: 09/08/2020
Var
nome: caracter
sobrenome: caracter
completo: caracter
Inicio
escreva ("Qual é o seu nome?")
 leia (nome)
 escreval()
escreva ("Qual é o seu sobrenomenome?")
 leia (sobrenome)
 escreval()
 
completo <- (nome + sobrenome)
 
 escreva ("seu nome completo é: ", completo)
 
 
 
Fimalgoritmo