Algoritmo "semnome"
// Função: Maior ou menor de 18
// Autor: Guilherme Nasciment de Oliveira
// Data: 09/08/2020
Var
primeiro: inteiro
segundo : inteiro

Inicio
escreva ("qual é o primeiro?")
leia (primeiro)
escreval()
escreva ("qual é o segundo?")
leia (segundo)
escreval()

 se (número <= 5)
 escreval ("esse número é maior)
   senao
  escreval ("esse número é menor")
  se (número <= 5) entao
 escreval ("esse número é maior)
   senao
  escreval ("esse número é menor")
  fimse

Fimalgoritmo