Algoritmo "semnome"
// Função: Dizer se o número é par ou impar
// Autor: Guilherme Nasciment de Oliveira
// Data: 10/08/2020
Var
numero1: inteiro
numero2: inteiro


Inicio
escreva ("Escreva um número: ")
 leia (numero1)
  escreval ()
   escreva ("Escreva um número: ")
    leia (numero2)
     escreval ()
     
     se (numero mod 2 = 0) entao
      escreva ("o número ", numero, " é par")
        senao
        escreva ("o número ", numero, " é impar")
        
        fimse


Fimalgoritmo