Algoritmo "semnome"
// Função: numeros positivos no vetor

// Autor: Guilherme Nascimento de Oliveira
// Data: 16/08/2020
Var
   contador: inteiro
   numero: vetor [0..14] de inteiro


Inicio
   para contador de 0 ate 14 faca
   escreval("Coloque um numero: ")
   leia(numero[contador])
fimpara
escreval ()
para contador de 0 ate 14 faca
   se (numero[contador]) > 0 entao
      escreva(" ",numero[contador])
   fimse
fimpara


Fimalgoritmo