Algoritmo "semnome"
// Função:

// Autor: Guilherme Nascimento de Oliveira
// Data: 17/08/2020

Var

volume , raio, altura : real

Inicio

escreval (" Qual é a altura da lata de óleo?")
 leia (altura)
  escreval ()
 escreval (" Qual é o raio da lata de óleo?")
  leia (raio)
   escreval()
 volume <- pi * raio * raio * altura
 
 escreval (" O volume da sua lata de óleo é,", volume, ".")

Fimalgoritmo