Algoritmo "semnome"
// Função: Ele uni dois vetores do mesmo tamanho e mesmo tipo em um terceiro vetor com dobro do tamanho.

// Autor: Guilherme Nascmento de Oliveira
// Data: 12/08/2020
Var

n: vetor [1..3] de inteiro
ct : inteiro
tt : inteiro
Inicio

para ct de 1 ate 2 passo 1  faca
     escreval ("qual o numero ?")
       leia (N[ct])
tt<- n[1]+n[2]
n[3] <- (n[1]+n[2])*2

fimpara
escreval ("a soma dos dois numeros é:",tt)
escreval ("o resultado em dobro dos numeros é:", n[3])

Fimalgoritmo